language: minimal

services:
  - docker

jobs:
  include:
    - stage: build test docker image
      script:
      - echo Building docker image for testing
      - make build-dev

    - stage: test
      script:
      - echo Running containerized tests
      - make test

    - stage: build release docker image
      if: branch = master
      script:
      - echo Building release docker image
      - make build-release

    - stage: Mark deployment in monitoring tools
      script:
      - echo Send notification to Grafana, Datadog etc
      - echo Not implemented

notifications:
  email: false
