FROM node:12.8

RUN groupmod -g 1001 node \
  && usermod -u 1001 -g 1001 node

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

EXPOSE 8080

ARG COMMIT_SHA
ENV ENV_COMMIT_SHA=${COMMIT_SHA}

CMD [ "npm", "run", "start" ]
